<script lang="ts">
	import { onMount } from 'svelte';
	import catalog from '$lib/data/catalog.json';

	/*
	 * Decorative, faded "restock" notifications that fade in and out around the
	 * edges of the hero, behind the headline — purely to make the hero feel live.
	 * Product names + prices come from a trimmed clone of the app catalog
	 * (src/lib/data/catalog.json, generated by scripts/build-hero-catalog.mjs).
	 *
	 * Store names are deliberately NOT shown. Each fixed slot rotates through the
	 * shuffled catalog over time, so the whole list gets airtime rather than a
	 * small hardcoded subset. The layer is aria-hidden, pointer-events-none,
	 * shown only on large screens, and disabled under prefers-reduced-motion.
	 */
	type Item = { name: string; price: string };

	const bellIcon =
		'M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0';

	// Fixed positions around the hero edges (kept clear of the centred text).
	const slots = [
		{ pos: 'top:9%; left:2%;', peak: 0.58 },
		{ pos: 'top:18%; right:2%;', peak: 0.5 },
		{ pos: 'top:28%; left:1%;', peak: 0.55 },
		{ pos: 'top:34%; right:3%;', peak: 0.48 },
		{ pos: 'top:62%; right:1%;', peak: 0.56 },
		{ pos: 'top:66%; left:2%;', peak: 0.5 },
		{ pos: 'top:78%; left:9%;', peak: 0.48 },
		{ pos: 'top:80%; right:8%;', peak: 0.55 },
		{ pos: 'top:89%; left:26%;', peak: 0.45 }
	];

	const items = catalog as Item[];

	// Deterministic initial order for SSR/hydration; shuffled after mount so each
	// visit differs without causing a hydration mismatch. Each slot starts at a
	// distinct index and advances by slots.length so it walks the whole catalog.
	let pool = $state<Item[]>(items);
	let slotState = $state(
		slots.map((_, i) => ({ idx: items.length ? i % items.length : 0, visible: false }))
	);

	onMount(() => {
		if (!pool.length) return;
		if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return;

		// Shuffle once on the client for per-visit variety.
		pool = [...pool].sort(() => Math.random() - 0.5);

		const timers: ReturnType<typeof setTimeout>[] = [];
		// Keep the slots evenly phased: with cycle = slots × STAGGER, each slot is
		// offset by exactly one stagger step, so only ~SHOW/STAGGER cards (≈2) are
		// visible at any moment instead of a cluster appearing together.
		const STAGGER = 1600;
		const SHOW = 3600;
		const HIDE = slots.length * STAGGER - SHOW;

		slots.forEach((_, i) => {
			const run = () => {
				slotState[i].visible = true;
				timers.push(
					setTimeout(() => {
						slotState[i].visible = false;
						timers.push(
							setTimeout(() => {
								slotState[i].idx = (slotState[i].idx + slots.length) % pool.length;
								run();
							}, HIDE)
						);
					}, SHOW)
				);
			};
			// Stagger each slot by one full step so they never bunch up.
			timers.push(setTimeout(run, i * STAGGER));
		});

		return () => timers.forEach(clearTimeout);
	});
</script>

<div class="pointer-events-none absolute inset-0 hidden overflow-hidden lg:block" aria-hidden="true">
	{#each slots as slot, i (i)}
		<div class="toast" class:is-visible={slotState[i].visible} style="{slot.pos} --peak:{slot.peak};">
			<span class="toast-icon">
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
					<path stroke-linecap="round" stroke-linejoin="round" d={bellIcon} />
				</svg>
			</span>
			<span class="toast-body">
				<span class="toast-top">Back in stock</span>
				<span class="toast-name">{pool[slotState[i].idx]?.name}</span>
				<span class="toast-price">{pool[slotState[i].idx]?.price}</span>
			</span>
		</div>
	{/each}
</div>

<style>
	.toast {
		position: absolute;
		display: flex;
		width: 17rem;
		align-items: flex-start;
		gap: 0.6rem;
		border-radius: 0.9rem;
		border: 1px solid var(--color-brand-cream-dark);
		background: #fff;
		padding: 0.7rem 0.85rem;
		box-shadow: 0 12px 30px -14px rgba(52, 50, 52, 0.45);
		opacity: 0;
		transform: translateY(10px) scale(0.98);
		transition:
			opacity 0.6s ease,
			transform 0.6s ease;
		will-change: opacity, transform;
	}
	.toast.is-visible {
		opacity: var(--peak);
		transform: translateY(0) scale(1);
	}

	.toast-icon {
		display: grid;
		height: 1.75rem;
		width: 1.75rem;
		flex-shrink: 0;
		place-items: center;
		border-radius: 9999px;
		background: var(--color-brand-sand-soft);
		color: var(--color-brand-red);
	}
	.toast-icon svg {
		height: 1rem;
		width: 1rem;
	}

	.toast-body {
		display: flex;
		min-width: 0;
		flex-direction: column;
		text-align: left;
	}
	.toast-top {
		font-size: 0.65rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.02em;
		color: var(--color-brand-charcoal-soft);
	}
	.toast-name {
		overflow: hidden;
		font-size: 0.8rem;
		font-weight: 700;
		line-height: 1.2;
		color: var(--color-brand-charcoal);
		display: -webkit-box;
		-webkit-box-orient: vertical;
		-webkit-line-clamp: 2;
		line-clamp: 2;
	}
	.toast-price {
		margin-top: 0.1rem;
		font-size: 0.8rem;
		font-weight: 600;
		color: var(--color-brand-red);
	}
</style>
